name: Prüfung Bash, JS, Python und Go Verfügbarkeit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v3

    - name: Prüfen, ob Bash verfügbar ist
      run: |
        if ! command -v bash &> /dev/null
        then
          echo "Bash ist nicht installiert!"
          exit 1
        else
          echo "Bash ist verfügbar!"
          bash --version
        fi

    - name: Prüfen, ob Node.js verfügbar ist
      run: |
        if ! command -v node &> /dev/null
        then
          echo "Node.js ist nicht installiert!"
          exit 1
        else
          echo "Node.js ist verfügbar!"
          node --version
        fi

    - name: Prüfen, ob Python verfügbar ist
      run: |
        if ! command -v python3 &> /dev/null
        then
          echo "Python ist nicht installiert!"
          exit 1
        else
          echo "Python ist verfügbar!"
          python3 --version
        fi

    - name: Prüfen, ob Go verfügbar ist
      run: |
        if ! command -v go &> /dev/null
        then
          echo "Go ist nicht installiert!"
          exit 1
        else
          echo "Go ist verfügbar!"
          go version
        fi

    - name: Bash-Skript ausführen
      run: |
        echo "Dies ist ein Bash-Testskript"
        bash -c "echo 'Hallo von Bash!'"

    - name: JavaScript-Datei ausführen
      run: |
        echo "console.log('Hallo von Node.js!');" > test.js
        node test.js

    - name: Python-Skript ausführen
      run: |
        echo "print('Hallo von Python!')" > test.py
        python3 test.py

    - name: Go-Skript ausführen
      run: |
        echo 'package main; import "fmt"; func main() { fmt.Println("Hallo von Go!") }' > test.go
        go run test.go
